#!/bin/sh

add_files=`git status -s $@ | egrep "^.(A|M)" | awk '{print $2}'`
for f in $add_files
do
    git add $f;
    echo add $f;
done

deleted_files=`git status -s $@ | egrep "^[^\s]*D[^\s]*\s" | awk '{print $2}'`
for f in $deleted_files
do
    git rm $f;
    echo rm $f;
done
