#!/bin/bash

. ./lib/lib.sh $@

./vim.sh $@
source $PROFILE

if [ "$withGo" == '1' ]
then
    ./go.sh $@
    source $PROFILE
fi

./cpp.sh $@
source $PROFILE

if [ "$isMac" == '0' ]
then
    test -f $PREFIX/bin/g++ && ./patchelf.sh $@
fi
