#!/bin/bash

# Install the vim and cppenviron.
# * It's contains software:
#       dos2unix
#       git
#       vim
#       g++
#       ctags
#       cmake
#       python-dev
#       vim-YouCompleteMe
#       vim-vundle
#       vim-airline
#       vim-nerdtree
#       vim-taglist
#       vim-cppenv.
#
# * And contains config files:
#       _vimrc
#       .ycm_extra_conf.py
#

# install dos2unix, git, vim, g++, ctags, cmake, python-dev

set -e

workdir=`pwd`
isMac=`uname -a | grep Darwin -c`
if [ "$isMac" == '1' ]
then
    brew --version || /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    brew update
    wget --version || brew install wget
    echo 'MacOS brew installed OK'
else
    sudo ./change_source_list.sh
fi

# config git address
VUNDLE_GIT=https://gitee.com/yyzybb537/Vundle.vim.git
YCM_GIT=https://gitee.com/yyzybb537/YouCompleteMe.git
CMAKE_GIT=https://gitee.com/yyzybb537/cmake.git

# install tool
INSTALL_TOOL="sudo apt-get"
INSTALL_SHOW="apt-cache show"
PY_NAME=python-dev
RUBY_DEV_NAME=ruby-dev
if [ `which apt-get 2>/dev/null | wc -l` -eq 0 ] ; then
    INSTALL_TOOL="sudo yum"
    INSTALL_SHOW="yum info"
    PY_NAME=python-devel
    RUBY_DEV_NAME=ruby-devel
fi
if [ "$isMac" == '1' ]
then
    INSTALL_TOOL=brew
    INSTALL_SHOW="brew info"
fi
echo "INSTALL_TOOL: $INSTALL_TOOL"

installPackage() {
    $INSTALL_SHOW $1 || $INSTALL_TOOL install -y $2
}

installProgram() {
    $1 --version || $INSTALL_TOOL install -y $2
}

compileVim() {
    echo "Start compileVim"
    installPackage libncurses5-dev
    installPackage $RUBY_DEV_NAME $RUBY_DEV_NAME
    installProgram python python
    installProgram python-config $PY_NAME
    installProgram ruby ruby
    git_clone https://gitee.com/yyzybb537/vim.git $HOME/.vim.git/vim
    cd $HOME/.vim.git/vim
    git reset --hard v7.4.2367
    git clean -f
    pyConfig=`python-config --configdir`
    ./configure --with-features=huge --enable-multibyte \
        --enable-pythoninterp=yes --enable-rubyinterp=yes \
        --enable-luainterp=yes --enable-perlinterp=yes \
        --with-python-config-dir=${pyConfig} \
        --enable-gui=gtk2 \
        --enable-cscope --prefix=/usr \
        --with-tlib=ncurses
    make
    sudo make install
    cd $workdir
}

installProgram dos2unix dos2unix
installProgram git git
g++ --version || $INSTALL_TOOL install g++ -y || $INSTALL_TOOL install gcc-c++ -y

if [ "$isMac" == "0" ]; then
    installProgram ctags ctags 
    locate --version || $INSTALL_TOOL install mlocate -y

    vim --version || compileVim
    vimVer=`vim --version | grep 1-2367 -c` ||
    if test ${vimVer} = "1"; then
        echo "No need compile Vim"
    else
        echo "Need compile Vim"
        compileVim
    fi
fi

# copy _vimrc file to $HOME
dos2unix _vimrc
rm $HOME/_vimrc -f
ln _vimrc $HOME/_vimrc || cp _vimrc $HOME/_vimrc
chmod 0666 $HOME/_vimrc
dos2unix .ycm_extra_conf.py
rm $HOME/.ycm_extra_conf.py -f
cp .ycm_extra_conf.py $HOME/
chmod 0666 $HOME/.ycm_extra_conf.py
vim_exe=`which vim`
vim_exe_dir=`dirname $vim_exe`
sudo ln -s ${vim_exe_dir}/vim ${vim_exe_dir}/v || echo ''

# git clone vim-vundle.git
vim_path=$HOME/.vim
vundle_path=${vim_path}/vimfiles/bundle/Vundle.vim
#echo $vim_path
#echo ${vundle_path}

git_clone()
{
    remote=$1
    dir=$2
    mkdir -p $dir

    cd $dir
    git status && git pull || git clone $remote .
    cd -
}

git_clone ${VUNDLE_GIT} ${vundle_path}

test_python_clang()
{
    sudo ldconfig
    echo 'import clang.cindex; s = clang.cindex.conf.lib' | python
}

version_large_or_equal()
{
    lhs=$1
    rhs=$2
    lhs_major=`echo $lhs | cut -d. -f1`
    lhs_minor=`echo $lhs | cut -d. -f2`
    lhs_num=`echo $lhs | cut -d. -f3`
    rhs_major=`echo $rhs | cut -d. -f1`
    rhs_minor=`echo $rhs | cut -d. -f2`
    rhs_num=`echo $rhs | cut -d. -f3`
    lhs_cmp=`expr $lhs_major \* 10000 + $lhs_minor \* 100 + $lhs_num`
    rhs_cmp=`expr $rhs_major \* 10000 + $rhs_minor \* 100 + $rhs_num`
    test $lhs_cmp -ge $rhs_cmp
}

install_cmake()
{
    cmake_ver=''
    cmake --version && cmake_ver=`cmake --version | grep version -i | sed 's/[^0-9.]//g'` || echo ''
    test ! -z $cmake_ver && version_large_or_equal $cmake_ver "3.4.3" && return 0 || echo ''

    cmake_dir=$HOME/.vim.git/cmake_cppenv
    git_clone $CMAKE_GIT $cmake_dir
    cd $cmake_dir

    tar zxf cmake.tar.gz
    ./bootstrap
    make
    sudo make install
    sudo ln -s /usr/local/bin/cmake /usr/bin/cmake || echo ''
}

install_cmake

# compile YouCompleteMe
ycm_path=${vim_path}/vimfiles/bundle/YouCompleteMe
git_clone ${YCM_GIT} ${ycm_path}
cd ${ycm_path}
./install.py --go-completer

# install other's vim-plugins
vim +BundleInstall -c quitall

#test_python_clang || echo "Error: python-clang install error, please check libclang.so and cindex.py!"
echo 'vim-go-env is ok, good luck!'

