#!/bin/bash

. ./lib/lib.sh $@

./vim.sh $@
source $PROFILE
./go.sh $@
source $PROFILE
./cpp.sh $@
source $PROFILE

# patchelf
patch_rpath()
{
    patchelf --set-rpath $HOME/lib:$HOME/lib64:$HOME/gcc/x86_64-pc-linux-gnu $1
}
for elf in `ls $HOME/bin`
do
    patch_rpath $elf
done
patch_rpath $VIMPATH/vimfiles/bundle/YouCompleteMe/third_party/ycmd/ycm_core.so

