#!/bin/bash

# Install the vim and cppenviron.
#
# * And contains config files:
#       _vimrc
#

. ../lib/lib.sh $@

set -e

# copy _vimrc to $HOME
which dos2unix && dos2unix _vimrc
rm $HOME/_vimrc -f
cp _vimrc $HOME/_vimrc
chmod 0666 $HOME/_vimrc

# clean and backup .vimrc
test -f $HOME/.vimrc && mv $HOME/.vimrc $HOME/.vimrc.`date "+%Y-%m-%dT%H:%M:%S"`

# alias v to vim
mkdir -p $HOME/bin
rm $HOME/bin/v -f
ln -s `which vim` $HOME/bin/v || echo -n
message 'vim-simple-env is ok, good luck!'

